basePath: /api/v1
definitions:
  domain.AuditLog:
    type: object
  domain.AuditLogStats:
    properties:
      action_counts:
        additionalProperties:
          type: integer
        type: object
      resource_counts:
        additionalProperties:
          type: integer
        type: object
      severity_counts:
        additionalProperties:
          type: integer
        type: object
      total_logs:
        type: integer
    type: object
  domain.Tenant:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      rate_limit:
        type: integer
      updated_at:
        type: string
    type: object
  dto.Error:
    properties:
      error:
        example: error message
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:10000
info:
  contact: {}
  description: This is a Audit log swagger server.
  title: Audit log Swagger API
  version: "1.0"
paths:
  /logs:
    get:
      description: Get a list of audit logs with filtering options
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: page_size
        type: integer
      - description: Filter by user ID
        in: query
        name: user_id
        type: string
      - description: Filter by action
        in: query
        name: action
        type: string
      - description: Filter by resource type
        in: query
        name: resource_type
        type: string
      - description: Filter by severity
        in: query
        name: severity
        type: string
      - description: Filter by start time (RFC3339)
        in: query
        name: start_time
        type: string
      - description: Filter by end time (RFC3339)
        in: query
        name: end_time
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.AuditLog'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: List audit logs
      tags:
      - audit_logs
    post:
      consumes:
      - application/json
      description: Create a new audit log entry
      parameters:
      - description: Audit log object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.AuditLog'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.AuditLog'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Create audit log
      tags:
      - audit_logs
  /logs/{id}:
    get:
      description: Get an audit log entry by its ID
      parameters:
      - description: Log ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.AuditLog'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Get audit log
      tags:
      - audit_logs
  /logs/bulk:
    post:
      consumes:
      - application/json
      description: Create multiple audit log entries in a single request
      parameters:
      - description: Array of audit log objects
        in: body
        name: body
        required: true
        schema:
          items:
            $ref: '#/definitions/domain.AuditLog'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/domain.AuditLog'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Bulk create audit logs
      tags:
      - audit_logs
  /logs/cleanup:
    delete:
      description: Delete audit logs older than specified days
      parameters:
      - description: Number of days to retain
        in: query
        name: days
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Delete old logs
      tags:
      - audit_logs
  /logs/export:
    get:
      description: Export audit logs with filtering options in JSON or CSV format
      parameters:
      - default: json
        description: Export format (json or csv)
        in: query
        name: format
        type: string
      - description: Filter by user ID
        in: query
        name: user_id
        type: string
      - description: Filter by action
        in: query
        name: action
        type: string
      - description: Filter by resource type
        in: query
        name: resource_type
        type: string
      - description: Filter by severity
        in: query
        name: severity
        type: string
      - description: Filter by start time (RFC3339)
        in: query
        name: start_time
        type: string
      - description: Filter by end time (RFC3339)
        in: query
        name: end_time
        type: string
      produces:
      - application/json
      - text/csv
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Export audit logs
      tags:
      - audit_logs
  /logs/stats:
    get:
      description: Get statistics about audit logs including counts by action, severity,
        and resource
      parameters:
      - description: Filter by start time (RFC3339)
        in: query
        name: start_time
        type: string
      - description: Filter by end time (RFC3339)
        in: query
        name: end_time
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.AuditLogStats'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Get log statistics
      tags:
      - audit_logs
  /tenants:
    get:
      description: Get a list of all tenants that the authenticated user has access
        to
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Tenant'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: List all tenants
      tags:
      - tenants
    post:
      consumes:
      - application/json
      description: Create a new tenant with specified configuration
      parameters:
      - description: Tenant object
        in: body
        name: tenant
        required: true
        schema:
          $ref: '#/definitions/domain.Tenant'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Tenant'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Create a new tenant
      tags:
      - tenants
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
